# Generated by Django 5.1.3 on 2024-12-02 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_contact_delete_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdiagnosis',
            name='next_checkup',
        ),
    ]
