# Generated by Django 5.1.3 on 2024-12-04 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_doctorprofile_pharmacistprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor'),
        ),
        migrations.DeleteModel(
            name='PharmacistProfile',
        ),
    ]
