# Generated by Django 5.1.3 on 2024-12-04 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_support'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Support',
        ),
    ]
