# Generated by Django 5.1.3 on 2024-12-04 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_support'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Support',
        ),
    ]
