# Generated by Django 5.1.3 on 2024-12-05 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_appointments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
